language: python
python:
  - "2.7"
services: postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "create role vmsadmin with createrole createdb login password '0xdeadbeef';" -U postgres
  - psql -c "CREATE DATABASE vms;" -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - export DJANGO_SECRET_KEY=foobarbaz
script:
  - cd vms
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput --traceback --settings=vms.settings
  - coverage run --source='.' manage.py test
after_success:
    coveralls --rcfile=.coveragerc
